# Generated by Django 4.0.3 on 2022-04-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moja_strona', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
