# Generated by Django 4.0.3 on 2022-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moja_strona', '0003_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=64)),
                ('delivery', models.IntegerField(choices=[('-1', 'courier'), ('0', 'parcel machine'), ('1', 'pick up in person')])),
                ('description', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
