# Generated by Django 4.0.3 on 2022-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moja_strona', '0009_alter_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
